Get new scenario file and annotate PR

diff --git a/.github/workflows/run-climate-assessment.yml b/.github/workflows/run-climate-assessment.yml
--- a/.github/workflows/run-climate-assessment.yml
+++ b/.github/workflows/run-climate-assessment.yml
@@ -13,6 +13,7 @@ jobs:
       # Give the default GITHUB_TOKEN write permission to commit and push the
       # added or changed files to the repository.
       contents: write
+      pull-requests: write
 
     steps:
     - name: Check out code
@@ -22,14 +23,61 @@ jobs:
       uses: actions/setup-python@v4
       with:
         python-version: "3.10"
+        cache: 'pip'
 
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.lock.txt 
 
+    - name: Get new scenario file
+      id: new-scenario-file
+      run: |
+        GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
+        PR_ID="${{github.event.number}}"
+        URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PR_ID}/files"
+        NEW_FILE=$(curl -s -L -H "Accept: application/vnd.github+json" \
+                                -H "Authorization: Bearer $GITHUB_TOKEN" \
+                                -H "X-GitHub-Api-Version: 2022-11-28" "$URL" \
+                                | jq -r '.[] | select((.filename | startswith("scenarios")) and (.status == "added")) | .filename') 
+        echo "$NEW_FILE"
+        if (( $(grep -c . <<<"$NEW_FILE") > 1 )); then
+          echo "Error: Only one scenario can be added in a Pull Request."
+          exit 1
+        else
+          echo "new_file=$NEW_FILE" >> $GITHUB_OUTPUT
+        fi 
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    
+    - name: New scenarios
+      run: |
+        echo "Newly added file in 'scenarios':"
+        echo "$SCENARIO_FILE"
+      env:
+        SCENARIO_FILE: ${{ steps.new-scenario-file.outputs.new_file }}
+        
     - name: Run pipeline
-      run: python run-climate-assessment.py
+      run: python run-climate-assessment.py $SCENARIO_FILE
+      env:
+        SCENARIO_FILE: ${{ steps.new-scenario-file.outputs.new_file }}
+      
+    - name: Setup cml
+      uses: iterative/setup-cml@v2
+      with:
+        vega: false
+
+    - name: Plot results
+      run: |
+        python create-plots.py $SCENARIO_FILE
+        echo 'Input: Scenario Emissions' > report.md
+        echo '![](./scenario-emissions.png)' >> report.md
+        echo 'Output: Climate Assessment' >> report.md
+        echo '![](./climate-assessment.png)' >> report.md  
+        cml comment create --publish report.md
+      env:
+        SCENARIO_FILE: ${{ steps.new-scenario-file.outputs.new_file }}
+        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
     - name: Commit results
       uses: stefanzweifel/git-auto-commit-action@v5
@@ -39,7 +87,6 @@ jobs:
         # Keep only CSV file with results, ignoring XLSX and other CSVs for now
         file_pattern: '*IAMC*.csv'
 
-        # Optional commit user and author settings
-        commit_user_name: Climate Assessment Bot # defaults to "github-actions[bot]"
+        commit_user_name: Climate Assessment Bot 
         commit_user_email: "<>"
         commit_author: "Climate Assessment Bot <>"
